"""writes ../../10_surfaces.md from ../tmp/surfaces.json (run surfaces.py first)"""
import os, json, collections
from common import *
J = json.load(open(os.path.join(TMP, 'surfaces.json')))
db = J['db']; tracks = J['tracks']
for d in tracks.values():                 # surfaces.py labels byte +0x18 'top' and +0x19 'base'; the names show it is the other way round
    for r in d['pairs']: r['top_id'], r['base_id'], r['top'], r['base'] = r['base_id'], r['top_id'], r['base'], r['top']
id2 = {}
for s in db:
    for i in s['ids']: id2['%08x' % i] = s['name']
# where is each id used as a road layer (track -> cells), and is the texture chunk present there
use = collections.defaultdict(lambda: collections.Counter())
for t, d in tracks.items():
    for r in d['pairs']:
        use[r['top_id']][t] += r['cells']; use[r['base_id']][t] += r['cells']
CLASSES = [('Tarmac (dry)', ['Tarmac_Top']), ('Tarmac (wet)', ['WetTarmac_Top']), ('Broken / dusty tarmac', ['BrokenTarmac', 'DustyBrokenTarmac']),
           ('Gravel', ['Gravel_Top']), ('Dry mud / dirt', ['DryMud_Top', 'Dry_Mud_Top', 'Dirt_Top']), ('Damp mud', ['DampMud_Top', 'Damp_Mud_Top']),
           ('Wet mud', ['WetMud_Top', 'Wet_Mud_Top']), ('Sand', ['Sand_Top', 'Sandy_Covering']), ('Snow', ['Snow_Top']), ('Ice', ['Ice_Top']),
           ('Slush', ['Slush']), ('Grass / swamp', ['Grass_Top', 'GrassySwamp_Top']), ('Cobbles', ['Cobbles_Top']), ('Wood (bridge)', ['Wood_Top']),
           ('Volcanic ash', ['VolcanicAsh']), ('Cattle grid', ['CattleGrid']), ('Water', ['Water'])]
def short(t): return t.replace('ps3/', 'R:').replace('demo/', 'D:')
o = []
o.append('# 10 - Surface types: which texture id selects which physics surface\n')
o.append('Generated by `work/scripts/gen_surface_doc.py` from `surfaces.py` output. Source of truth: the two lists the exe')
o.append('walks in 0x5B1820 - `SurfacePairEffects\\surfacepairdata_xdata.sbf`, root +0x2C (linked list `{next, name hash, global')
o.append('index, name}`) and root +0x30 (parallel linked list `{next, count, texture ids}`), 90 entries. VERIFIED: every one of the')
o.append('road-layer ids of the 6 arcade tracks, the 2 Revo demo tracks and the 24 converted Revo tracks is found in these lists')
o.append('except 2 (Canyon4 008a2850, one in Lakeside4), which fall back to global surface 0.\n')
o.append('How a road cell uses them (04_trackdeform_road.md): byte +0x18 of a cell is its BASE layer (what is under the')
o.append('surface, shown where the road is worn/deformed), byte +0x19 its TOP layer. VERIFIED by names: in every track the')
o.append('+0x18 ids resolve to `..._Base` entries and the +0x19 ids to `..._Top` entries (a few Desert4/Lakeside cells use a')
o.append('Top entry in both). An importer picks a (base id, top id) pair that SEGA uses together, lists both ids in the road')
o.append('chunk tables, and must ship both texture chunks (kind 4, DXT5 1024x1024) under those ids; the pixels may be replaced.\n')
o.append('Track name prefixes below: none = arcade track, `D:` = Revo PC demo, `R:` = Revo PS3 track converted to PC')
o.append('(`F:\\Jogos\\_revo_ps3_converted`). Cell counts are road cells using the id in that track.\n')
o.append('## Importer table: "I want X" -> ids\n')
for cname, keys in CLASSES:
    ents = [s for s in db if any(k in s['name'] for k in keys) and not s['name'].endswith('_Base')]
    if cname.startswith('Gravel'): ents = [s for s in ents if 'Gravel' in s['name']]
    if cname == 'Tarmac (dry)': ents = [s for s in ents if 'Wet' not in s['name'] and 'Broken' not in s['name']]
    if cname == 'Sand': ents = [s for s in ents if 'Sand' in s['name']]
    if cname == 'Snow': ents = [s for s in ents if 'Ice' not in s['name']]
    o.append('### %s\n' % cname)
    o.append('| Terrain entry (global index) | Recommended pair: base id + top id | Found in |'); o.append('|---|---|---|')
    for s in ents:
        best = collections.Counter()
        for t, d in tracks.items():
            for r in d['pairs']:
                if s['name'] in r['top']: best[(r['base_id'], r['top_id'], '/'.join(r['base']))] += r['cells']
        if not best:
            o.append('| %s (%d) | not used as a top layer by any track examined (%d ids in the list) | - |' % (s['name'], s['index'], len(s['ids']))); continue
        (b, tp, bn), n = best.most_common(1)[0]
        where = collections.Counter()
        for t, d in tracks.items():
            for r in d['pairs']:
                if r['base_id'] == b and r['top_id'] == tp: where[t] += r['cells']
        o.append('| %s (%d) | base `%s` (%s) + top `%s` | %s |' % (s['name'], s['index'], b, bn, tp, ', '.join('%s %d' % (short(t), c) for t, c in where.most_common(4))))
    o.append('')
o.append('## Audio cross-check\n')
o.append('`Audio\\SFX_HashCode.h` has one tyre loop and one kick-up per audible class: Tyre{DryTarmac, WetTarmac, BrokenTarmac, DryGravel,')
o.append('DryMud, DampMud, WetMud, Sand, Snow, Ice, Slush, Grass, SwampGrass, Soil, StoneCobbles, WoodenBridge, VolcanicAsh, CattleGrid,')
o.append('DeepWater} and Kickup{Tarmac, BrokenTarmac, Gravel, Mud, DampMud, WetMud, Sand, Snow, Slush, Grass, Soil, StoneCobbles,')
o.append('CattleGrid, DeepWater}; the exe has the matching strings `SurfaceTarmac ... SurfaceVolcanicAsh` at 0x6B1C48-0x6B2204.')
o.append('The 90 terrain entries are finer than the audio classes (per-environment variants of the same class). Which audio class')
o.append('each terrain entry plays is stored in the terrain property chunks (root +0x1C..+0x24, +0x44 of the same file) and was')
o.append('NOT decoded: the class in the headings above is inferred from the entry NAME (LIKELY).\n')
o.append('## All 90 terrain entries\n')
o.append('| Index | Name | Ids in list | Ids used by examined tracks (track: cells) |'); o.append('|---|---|---|---|')
for s in sorted(db, key=lambda s: s['index']):
    used = []
    for i in s['ids']:
        k = '%08x' % i
        if use[k]: used.append('`%s` (%s)' % (k, ', '.join('%s: %d' % (short(t), c) for t, c in use[k].most_common(3))))
    o.append('| %d | %s | %d | %s |' % (s['index'], s['name'], len(s['ids']), '; '.join(used[:6]) or '-'))
o.append('\n## Per track: layer pairs in use (top 6)\n')
for t, d in tracks.items():
    o.append('- **%s** (%d layer ids): ' % (short(t), len(d['ids'])) + '; '.join('%s+%s %s/%s x%d' % (r['base_id'], r['top_id'], '/'.join(r['base']).replace('Terrain_', ''), '/'.join(r['top']).replace('Terrain_', ''), r['cells']) for r in d['pairs'][:6]))
o.append('\n## Boundary (wall) surfaces\n')
o.append('The wall chunk has its own id table (06_boundary_collision.md). Those ids are looked up in the same file, root +0x04:')
o.append('a linked list of 31 groups `{next, ->{count, ids}, flag, 0}`, parallel to the 31 names of root +0x14')
o.append('(`CarToCar_*`, `Boundary_Armco, Brick, Metal, Mud, Plastic, Rock, Tyres, Wood, Vegetation, Snow, None`, then')
o.append('per-environment variants). Group membership found: floor/ceiling ids of Stadium (ee64dc3d), Alpine/Lakeside/Desert')
o.append('(a76a4869), Tropical (2d1caef9), Canyon (7d91807d) are all in group 0; Stadium walls e2671eda in group 20, 3ac3a983 in')
o.append('group 6; Lakeside walls 5648af3a in group 5. The group -> name pairing was not pinned down (UNKNOWN); the builder')
o.append('simply reuses the slot\'s own most common wall id and floor id.')
open(os.path.join(os.path.dirname(WORK), '10_surfaces.md'), 'w').write('\n'.join(o) + '\n')
print('written', len(o), 'lines')
